
name: CI

on:
  push:
    branches:
      - main

jobs:
  flake-check:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        check: [ "clippy-check", "docs-check", "fmt-check", "deny-check", "nextest-check" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run flake checks
        run: nix build "./#checks.x86_64-linux.${{ matrix.check }}" -L
